image: ubuntu2004

before_install:
  - chmod +x ./flaskapp/st.sh

install:
  - sudo apt-get update
  - sudo apt-get install -y python3 python3-pip
  - pip3 install -r ./flaskapp/requirements.txt

test_script:
  - cd flaskapp
  - ./st.sh