image: ubuntu2404

install:
  - chmod +x ./flaskapp/st.sh
  - sudo apt-get update
  - sudo apt-get install -y python3.11 python3.11-pip
  - pip3 install -r ./flaskapp/requirements.txt

test_script:
  - cd flaskapp
  - ./st.sh