image: ubuntu2004

install:
  # Обновление списка пакетов
  - sudo apt-get update

  # Добавление PPA deadsnakes
  - sudo add-apt-repository ppa:deadsnakes/ppa -y
  - sudo apt-get update

  # Установка Python 3.11 и pip
  - sudo apt-get install -y python3.11 python3.11-distutils
  - curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11

  # Сделать скрипт исполняемым
  - chmod +x ./flaskapp/st.sh

  # Установка зависимостей из requirements.txt
  - python3.11 -m pip install -r ./flaskapp/requirements.txt

test_script:
  # Переход в директорию flaskapp
  - cd flaskapp

  # Запуск скрипта st.sh
  - ./st.sh