image: ubuntu2204

install:
  - sudo apt-get update
  - sudo apt-get install -y python3.11 python3.11-distutils
  - wget https://bootstrap.pypa.io/get-pip.py
  - sudo python3.11 get-pip.py
  - chmod +x ./flaskapp/st.sh
  - pip install -r ./flaskapp/requirements.txt

test_script:
  - cd flaskapp
  - ./st.sh