image: ubuntu2204

install:
  - sudo apt-get update
  - sudo apt-get update
  - sudo apt-get install -y python3.11 python3.11-distutils
  - chmod +x ./flaskapp/st.sh
  - python3.11 -m pip install -r ./flaskapp/requirements.txt

test_script:
  - cd flaskapp
  - ./st.sh